### ISSUE TITLE
[bug]: NextCloud mount is wrong

### ISSUE THREAD

**Issue by auggie-lahey** [Start9Labs/jellyfin-startos#11]
### Prerequisites

- [X] I have searched for existing issues that already report this problem.

### Device

Laptop/Desktop

### Device OS

Linux

### Device OS Version

0.3.5~1

### Browser

Brave

### Browser Version

1.62.162

### Current Behavior

/mnt/nextcloud doesn't show any media folders, only the directories for the app itself. 
(3rd party, apps, config, core, data, etc.)
Regular filebrowser works

### Expected Behavior

i should just be able to put /mnt/nextcloud/Movies and the folder load. I even tried the way mentioned here: https://github.com/Start9Labs/jellyfin-startos/pull/10

with the username and it still doesn't work 

### Steps to Reproduce

Just try to use jellyfin with nextcloud, the folder menu will be wrong. 

### Anything else?

![Screenshot from 2024-02-10 20-48-22](https://github.com/Start9Labs/jellyfin-startos/assets/15633227/e65bb20f-b576-435f-91ec-27a73a5eb18c)

**Comment by Dominion5254** [comment]
The contents of `mnt/nextcloud` appear as I would expect.

Your Movies directory is likely nested within data > username > Movies

**Comment by kn0wmad** [comment]
Closing as solved, please let us know if you still have an issue @auggie-lahey
